name: CI/CD

on:
  push:
    branches: 
      - main

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Yandex Cloud Container Registry
        uses: yc-actions/yc-cr-login@v2
        with:
          yc-sa-json-credentials: ${{ secrets.YC_KEY_TEST }}

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./infrastructure/docker/app/Dockerfile
          push: true
          tags: cr.yandex/crp4640u3tckkugq0upa/organization-app:${{ github.sha }}