name: CI/CD

on:
  push:
    branches: 
      - main

jobs:
  docker:
    name: Prepare Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Yandex Cloud Container Registry
        uses: yc-actions/yc-cr-login@v2
        with:
          yc-sa-json-credentials: ${{ secrets.YC_KEY_TEST }}

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./infrastructure/docker/app/Dockerfile
          push: true
          tags: cr.yandex/crp4640u3tckkugq0upa/organization-app:${{ github.sha }}

  terraform:
    name: Deploy infrastructure
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.1.7"

      - name: Terraform Init
        run: terraform init
        working-directory: ./infrastructure/terraform

      - name: Terraform Plan
        run: terraform plan
        working-directory: ./infrastructure/terraform

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: ./infrastructure/terraform

      - name: Terraform Destroy
        run: terraform destroy -auto-approve
        working-directory: ./infrastructure/terraform